---
name: cmpsc-100-week-2-functions
break: true
indent: 4
---

activities/analog/writing/reflection.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountFileParagraphs --count 5

activities/digital/digital-1-functions.ipynb:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    
activities/digital/digital-1-functions.py:
    MatchFileFragment --fragment "input(" --count 2 --exact
    MatchFileFragment --fragment "int(" --count 1
    MatchFileFragment --fragment "def estimate_piano_tuners(" --count 1 --exact
    MatchFileFragment --fragment "return " --count 1 --exact
    MatchFileFragment --fragment "round(" --count 1 --exact
    CountSingleLineComments --count 3 --language Python

lab/week-2-lab.py:
    MatchFileFragment --fragment "def " --count 3
    MatchFileFragment --fragment "int(" --count 1
    MatchFileFragment --fragment "round(" --count 1
    MatchFileFragment --fragment "input(" --count 1 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountSingleLineComments --count 7 --language Python
    
lab/writing/reflection.md:
    CountFileWords --count 250
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountFileParagraphs --count 5
    
ExecuteCommand --command "python lab/week-2-lab.py < lab/.scenario_4"
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_1" --fragment "369285" --count 1 --exact
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_1" --fragment "185 window washers" --count 1 --exact
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_2" --fragment "3692" --count 1 --exact
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_2" --fragment "2 window washers" --count 1 --exact
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_3" --fragment "45545238" --count 1 --exact
MatchCommandFragment --command "python lab/week-2-lab.py < lab/.scenario_3" --fragment "22773 window washers" --count 1 --exact
CountCommits --count 5