---
name: cmpsc-100-week-2-functions
break: true
indent: 4
---

activities/analog/writing/reflection.md:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    CountFileParagraphs --count 5

activities/digital/digital-1-functions.ipynb:
    MatchFileFragment --fragment "TODO" --count 0 --exact
    
activities/digital/digital-1-functions.py:
    MatchFileFragment --fragment "input(" --count 2 --exact
    MatchFileFragment --fragment "int(" --count 1
    MatchFileFragment --fragment "def estimate_piano_tuners(" --count 1 --exact
    MatchFileFragment --fragment "return " --count 1 --exact
    MatchFileFragment --fragment "round(" --count 1 --exact
    CountSingleLineComments --count 3 --language Python   
    
CountCommits --count 5
MatchCommandFragment --command "python activities/digital/digital-1-functions.py < .case" --fragment "30" --count 1 --exact 
